# This is a docker image containing docker and a Nix store.
# This enables to either run Docker images inside this one,
# or use `nix develop` to start a sandboxed environment to
# do other non-docker related stuff.

FROM docker.nix-community.org/nixpkgs/cachix-flakes as base

LABEL org.opencontainers.image.source https://github.com/sdsc-ordes/tripsu
LABEL org.opencontainers.image.description "CI container image for tripsu"
LABEL org.opencontainers.image.license "Apache"

# Nix Image
# ===============================================
FROM base as ci-nix

RUN [ "TARGETPLATFORM" = "linux/amd64" ] || echo "Platform not yet supported."
COPY ./tools /container-setup/tools

# Install Nix.
RUN bash -c ". /container-setup/tools/general.sh && ci_setup_nix"

# Bootstrap the Nix store with some basic utilities.
RUN cd /container-setup && \
    git init && git add . && \
    nix profile install --profile /nix/var/nix/profiles/ci \
    --accept-flake-config "./tools/nix#ci.bootstrap" --impure && \
    nix store optimise

ENV PATH="/nix/var/nix/profiles/ci/bin:$PATH"
