name: rdf-protect

on: [push]

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mirror + Trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/<namespace>/<repository>"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "true"
          GITLAB_HOSTNAME: "gitlab.datascience.ch"
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "454"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
