remote_theme: pages-themes/cayman@v0.2.0
title: tripsu
description: Pseudonymize specific triples in a knowledge graph, with speed and accuracy. 🥷
markdown: kramdown
  toc_levels: 1..3
plugins:
  - jemoji
  - jekyll-remote-theme
ler
