# This is a docker image containing docker and a Nix store.
# This enables to either run Docker images inside this one,
# or use `nix develop` to start a sandboxed environment to
# do other non-docker related stuff.

FROM alpine:latest as base-podman
LABEL org.opencontainers.image.source https://github.com/sdsc-ordes/rdf-protect
LABEL org.opencontainers.image.description "CI container image for rdf-protect"
LABEL org.opencontainers.image.license "Apache"

RUN apk add findutils coreutils git jq curl bash just parallel podman

# Nix Image
# ===============================================
FROM base-podman as ci-nix
RUN [ "TARGETPLATFORM" = "linux/amd64" ] || echo "Platform not yet supported."
COPY ./tools /container-setup/tools

# Install Nix and pre-cache the env.
RUN bash -c ". /container-setup/tools/general.sh && ci_setup_nix"
COPY rust-toolchain.toml /container-setup/
RUN cd /container-setup && \
    git init && git add . && \
    nix --accept-flake-config \
    build --no-link "./tools/nix#devShells.x86_64-linux.ci" && \
    nix store gc && \
    nix store optimise

# Format image.
# ===============================================
FROM ci-nix as ci-format

# Lint image.
# ===============================================
FROM ci-nix as ci-lint

# Build image.
# ===============================================
FROM ci-nix as ci-build
