# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: rdf-protect

on:
  push:
    branches:
      - main
      - "feat/*"
      - "fix/*"

  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sdsc-ordes/rdf-protect:ci-format-1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 1 - format
        run: |
          source .gitlab/scripts/before-script.sh
          just nix-develop-ci just format

  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sdsc-ordes/rdf-protect:ci-lint-1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 2 - lint
        run: |
          source .gitlab/scripts/before-script.sh &&
          just nix-develop-ci just lint

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sdsc-ordes/rdf-protect:ci-build-1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 3 - build
        run: |
          source .gitlab/scripts/before-script.sh &&
          just nix-develop-ci just build
