name: Main and PR Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      # This is not a real version tag, its just used to trigger
      # the release build. Glob pattern:
      - "prepare-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    uses: ./.github/workflows/normal.yaml
    with:
      is_release: true
